apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: dev
spec:
  project: default
  source:
    repoURL: https://github.com/Slava-png/argo-practice
    targetRevision: HEAD
    path: ./env/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: 
      prune: true
      selfHeal: true
    excludeResources:
      - "limitranges/v1"
      - "resourcequotas/v1"