apiVersion: v1
kind: Service
metadata:
  name: cluster-svc-for-deploy
  namespace: app
  labels:
    svc: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
